# MenstruAI Quiz Question Bank (88 Unique Evidence-Based Questions)
# Spanning 12 Knowledge Categories with Easy, Medium, and Hard Difficulties

QUIZ_QUESTION_BANK = [
    # ==========================================
    # 1. MENSTRUAL HEALTH BASICS
    # ==========================================
    {
        "question": "What is the typical physiological length range for an adult menstrual cycle?",
        "category": "Menstrual Health Basics",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "While 28 days is a textbook average, clinical guidelines define normal adult cycles as ranging between 21 and 35 days.",
        "options": [
            ("Exactly 28 days without variation", False),
            ("Between 21 and 35 days", True),
            ("Between 10 and 18 days", False),
            ("Between 40 and 60 days", False),
        ],
    },
    {
        "question": "Which biological day is universally defined as Day 1 of the menstrual cycle?",
        "category": "Menstrual Health Basics",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Day 1 is marked by the first day of full, bright red menstrual flow, rather than minor pre-menstrual spotting.",
        "options": [
            ("The day ovulation occurs", False),
            ("The day bleeding completely ceases", False),
            ("The first day of full menstrual bleeding", True),
            ("The midpoint of the calendar month", False),
        ],
    },
    {
        "question": "What is the average duration of menstrual bleeding in a typical cycle?",
        "category": "Menstrual Health Basics",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Normal menstrual bleeding usually lasts between 3 and 7 days, with the heaviest volume on the first two days.",
        "options": [
            ("1 to 2 hours", False),
            ("3 to 7 days", True),
            ("14 to 21 days", False),
            ("Exactly 10 days for everyone", False),
        ],
    },
    {
        "question": "What uterine layer sheds during menstruation when pregnancy does not occur?",
        "category": "Menstrual Health Basics",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "The endometrium is the inner functional mucosal lining of the uterus that proliferates each cycle and sheds during menses.",
        "options": [
            ("Myometrium", False),
            ("Perimetrium", False),
            ("Endometrium", True),
            ("Epimetrium", False),
        ],
    },
    {
        "question": "Which hormone surge directly triggers the release of an egg during ovulation?",
        "category": "Menstrual Health Basics",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "A rapid surge in Luteinizing Hormone (LH) from the pituitary gland triggers follicular rupture and ovum release.",
        "options": [
            ("Luteinizing Hormone (LH)", True),
            ("Thyroid Stimulating Hormone (TSH)", False),
            ("Prolactin", False),
            ("Cortisol", False),
        ],
    },
    {
        "question": "What structure forms in the ovary after ovulation to secrete progesterone?",
        "category": "Menstrual Health Basics",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "The collapsed ovarian follicle transforms into the corpus luteum, which secretes progesterone during the luteal phase.",
        "options": [
            ("Corpus albicans", False),
            ("Corpus luteum", True),
            ("Graafian follicle", False),
            ("Blastocyst", False),
        ],
    },
    {
        "question": "True or False: Anovulatory cycles (cycles where no egg is released) can still produce vaginal bleeding.",
        "category": "Menstrual Health Basics",
        "difficulty": "Hard",
        "question_type": "true_false",
        "explanation": "True. In anovulatory cycles, estrogen stimulates the endometrium until it outgrows its vascular supply, causing estrogen breakthrough bleeding.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "Why is the menstrual cycle recognized by major medical academies as the 'fifth vital sign'?",
        "category": "Menstrual Health Basics",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Cycle regularity reflects overall systemic endocrine, metabolic, and nutritional well-being alongside pulse, respiration, blood pressure, and temperature.",
        "options": [
            ("It determines blood type", False),
            ("It reflects systemic hormonal, nutritional, and metabolic health", True),
            ("It replaces blood pressure testing", False),
            ("It only indicates immediate fertility status", False),
        ],
    },

    # ==========================================
    # 2. MENSTRUAL HYGIENE
    # ==========================================
    {
        "question": "What is the recommended maximum interval to change a disposable pad during regular daytime use?",
        "category": "Menstrual Hygiene",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Changing pads every 4 to 6 hours prevents bacterial proliferation, skin irritation, and unpleasant odors.",
        "options": [
            ("Every 12 hours", False),
            ("Every 4 to 6 hours", True),
            ("Once every 24 hours", False),
            ("Only when it leaks", False),
        ],
    },
    {
        "question": "What is the recommended water temperature and technique for washing the external vulva?",
        "category": "Menstrual Hygiene",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Warm water alone or an extremely gentle, fragrance-free cleanser externally is recommended; harsh soaps strip natural protective barriers.",
        "options": [
            ("Boiling water with antibacterial scrub", False),
            ("Lukewarm water, cleansing gently front-to-back", True),
            ("Cold water with perfumed shower gels", False),
            ("Alcohol wipes inside the vaginal canal", False),
        ],
    },
    {
        "question": "Why is wiping front-to-back after using the restroom essential during menstruation?",
        "category": "Menstrual Hygiene",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Wiping front-to-back prevents transferring rectal bacteria (such as E. coli) into the urethra and vaginal opening.",
        "options": [
            ("It prevents intestinal bacteria from entering the urinary and reproductive tracts", True),
            ("It alters cycle duration", False),
            ("It prevents menstrual cramps", False),
            ("It speeds up flow volume", False),
        ],
    },
    {
        "question": "What is the natural, healthy acidic pH range of the adult vaginal environment?",
        "category": "Menstrual Hygiene",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Normal vaginal pH ranges from 3.8 to 4.5, maintained by lactic acid-producing Lactobacillus species to inhibit pathogens.",
        "options": [
            ("pH 1.0 to 2.0 (strongly acidic)", False),
            ("pH 3.8 to 4.5 (moderately acidic)", True),
            ("pH 7.0 (neutral)", False),
            ("pH 9.0 to 10.0 (strongly alkaline)", False),
        ],
    },
    {
        "question": "Why is internal vaginal douching strongly discouraged by gynecological organizations?",
        "category": "Menstrual Hygiene",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Douching washes away protective lactobacilli, elevates pH, and increases the risks of bacterial vaginosis and pelvic inflammatory disease.",
        "options": [
            ("It stops menstrual bleeding prematurely", False),
            ("It eliminates protective flora and increases infection risk", True),
            ("It causes immediate severe dehydration", False),
            ("It prevents tampon insertion", False),
        ],
    },
    {
        "question": "True or False: Wearing damp or sweat-soaked underwear for extended periods during menstruation increases candidiasis (yeast infection) risk.",
        "category": "Menstrual Hygiene",
        "difficulty": "Medium",
        "question_type": "true_false",
        "explanation": "True. Warm, moist environments facilitate rapid fungal proliferation, particularly Candida albicans.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "How should reusable cloth pads or period underwear be laundered to maintain hygiene and absorbency?",
        "category": "Menstrual Hygiene",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Rinsing in cold water first prevents protein stain setting, followed by thorough washing with mild detergent and full air drying in sunlight.",
        "options": [
            ("Bleached with chlorine and never dried", False),
            ("Rinsed in cold water, washed with mild soap, and thoroughly dried", True),
            ("Soaked in boiling water for 3 days without soap", False),
            ("Dry cleaned only", False),
        ],
    },
    {
        "question": "Which bacteria is most commonly implicated in staphylococcal Toxic Shock Syndrome (TSS)?",
        "category": "Menstrual Hygiene",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Staphylococcus aureus produces TSST-1 toxin under prolonged hyper-absorbent aerobic conditions, causing high fever and shock.",
        "options": [
            ("Staphylococcus aureus", True),
            ("Lactobacillus crispatus", False),
            ("Helicobacter pylori", False),
            ("Escherichia coli", False),
        ],
    },

    # ==========================================
    # 3. MENSTRUAL PRODUCTS
    # ==========================================
    {
        "question": "What is the maximum continuous wear time recommended for a tampon to minimize TSS risks?",
        "category": "Menstrual Products",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Medical guidelines consistently advise changing tampons every 4 to 8 hours, never exceeding 8 hours.",
        "options": [
            ("4 to 8 hours", True),
            ("16 to 24 hours", False),
            ("48 hours", False),
            ("Until pain occurs", False),
        ],
    },
    {
        "question": "Which menstrual product collects menstrual fluid internally rather than absorbing it?",
        "category": "Menstrual Products",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Menstrual cups and discs are made of medical-grade silicone or TPE and collect fluid internally rather than absorbing moisture.",
        "options": [
            ("Disposable pads", False),
            ("Panty liners", False),
            ("Menstrual cups", True),
            ("Cotton balls", False),
        ],
    },
    {
        "question": "How should a reusable silicone menstrual cup be sanitized between menstrual cycles?",
        "category": "Menstrual Products",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Boiling the cup in a pot of water for 5 to 10 minutes sterilizes bacteria before storing it in a breathable pouch.",
        "options": [
            ("Wiped with petroleum jelly", False),
            ("Boiled in water for 5 to 10 minutes", True),
            ("Placed in a domestic microwave dry", False),
            ("Left submerged in bleach overnight", False),
        ],
    },
    {
        "question": "When choosing tampon absorbency, which medical principle should be followed?",
        "category": "Menstrual Products",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Always use the lowest absorbency suitable for your actual flow to prevent vaginal dryness and reduce TSS risks.",
        "options": [
            ("Always use Super Plus regardless of flow", False),
            ("Select the lowest absorbency necessary for your flow", True),
            ("Use two tampons simultaneously", False),
            ("Choose based entirely on fragrance", False),
        ],
    },
    {
        "question": "What is the primary anatomical difference between a menstrual cup and a menstrual disc?",
        "category": "Menstrual Products",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Cups sit in the vaginal canal secured by suction; discs sit deeper in the vaginal fornix beneath the cervix and are held by the pubic bone.",
        "options": [
            ("Discs sit in the vaginal fornix below the cervix; cups sit in the lower canal", True),
            ("Cups are only for teenagers; discs are for seniors", False),
            ("Discs absorb blood; cups dissolve it", False),
            ("There is no anatomical difference", False),
        ],
    },
    {
        "question": "True or False: Flushing sanitary pads or tampons down the toilet is safe for modern residential plumbing.",
        "category": "Menstrual Products",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "False. Pads and tampons expand upon contact with water and do not disintegrate like toilet paper, causing severe blockages and environmental contamination.",
        "options": [
            ("True", False),
            ("False", True),
        ],
    },
    {
        "question": "What material is commonly used in medical-grade menstrual cups due to its biocompatibility?",
        "category": "Menstrual Products",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Medical-grade silicone is hypoallergenic, non-porous, and resistant to bacterial colonization.",
        "options": [
            ("Latex rubber only", False),
            ("Medical-grade silicone or TPE", True),
            ("Polyurethane foam", False),
            ("Recycled vinyl", False),
        ],
    },

    # ==========================================
    # 4. SYMPTOMS & PAIN
    # ==========================================
    {
        "question": "What lipid compounds produced by the endometrium are responsible for primary menstrual cramping?",
        "category": "Symptoms",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Prostaglandins trigger myometrial (uterine muscle) contractions to shed the lining. Elevated levels cause primary dysmenorrhea.",
        "options": [
            ("Prostaglandins", True),
            ("Insulin", False),
            ("Adrenaline", False),
            ("Bile acids", False),
        ],
    },
    {
        "question": "What is the medical term for painful menstruation that interferes with daily functioning?",
        "category": "Symptoms",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Dysmenorrhea is the clinical term for painful menstrual cramps. Primary is without pelvic pathology; secondary involves an underlying condition.",
        "options": [
            ("Amenorrhea", False),
            ("Dysmenorrhea", True),
            ("Menorrhagia", False),
            ("Oligomenorrhea", False),
        ],
    },
    {
        "question": "Applying a heating pad (around 40°C) to the lower abdomen helps relieve cramps primarily by doing what?",
        "category": "Symptoms",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Thermal heat vasodilates pelvic blood vessels, improving blood flow and reducing ischemic muscle spasms in the uterus.",
        "options": [
            ("Freezing pain nerve terminals", False),
            ("Promoting muscle relaxation and pelvic blood flow", True),
            ("Stopping hormonal production instantly", False),
            ("Thinning out the uterine walls", False),
        ],
    },
    {
        "question": "What causes premenstrual water retention and abdominal bloating before menstruation?",
        "category": "Symptoms",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Shifts in estrogen and progesterone in the luteal phase stimulate the renin-angiotensin-aldosterone system, promoting temporary sodium and water retention.",
        "options": [
            ("Rapid loss of stomach volume", False),
            ("Progesterone and estrogen shifts promoting sodium and fluid retention", True),
            ("Excessive stomach bacteria growth", False),
            ("Complete kidney shutdown", False),
        ],
    },
    {
        "question": "What distinguishes primary dysmenorrhea from secondary dysmenorrhea?",
        "category": "Symptoms",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Primary dysmenorrhea is cramping without identifiable pelvic pathology; secondary is caused by underlying conditions like endometriosis or fibroids.",
        "options": [
            ("Primary only affects older adults; secondary affects teens", False),
            ("Primary has no underlying pelvic pathology; secondary stems from clinical conditions", True),
            ("Primary happens once in a lifetime; secondary occurs monthly", False),
            ("Secondary only causes headaches, not abdominal cramps", False),
        ],
    },
    {
        "question": "Why can hormonal migraines occur right before or during the first days of menstruation?",
        "category": "Symptoms",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "The rapid drop in circulating estrogen levels at the end of the luteal phase triggers neurovascular hypersensitivity in susceptible individuals.",
        "options": [
            ("Sharp estrogen withdrawal triggering neurovascular sensitization", True),
            ("Excessive hemoglobin accumulation", False),
            ("High blood sugar surges", False),
            ("Permanent retinal nerve compression", False),
        ],
    },
    {
        "question": "True or False: Breast tenderness (mastalgia) in the premenstrual phase is commonly linked to elevated progesterone and prolactin sensitivity.",
        "category": "Symptoms",
        "difficulty": "Medium",
        "question_type": "true_false",
        "explanation": "True. Luteal phase progesterone promotes ductal and glandular proliferation in breast tissue, often creating temporary fullness or tenderness.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "What physiological condition involves endometrial tissue growing outside the uterus, causing severe chronic pelvic pain?",
        "category": "Symptoms",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Endometriosis occurs when endometrium-like tissue implants on ovaries, fallopian tubes, and pelvic peritoneum, producing inflammation and scarring.",
        "options": [
            ("Endometriosis", True),
            ("Psoriasis", False),
            ("Cholecystitis", False),
            ("Hypothyroidism", False),
        ],
    },

    # ==========================================
    # 5. NUTRITION & HYDRATION
    # ==========================================
    {
        "question": "Why is dietary iron replenishment especially valuable during and after menstruation?",
        "category": "Nutrition",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Red blood cells shed during bleeding contain iron-rich hemoglobin; dietary iron prevents microcytic anemia and fatigue.",
        "options": [
            ("To maintain healthy hemoglobin levels depleted by blood loss", True),
            ("To increase bone calcium directly", False),
            ("To stop menstrual flow from occurring", False),
            ("To induce rapid weight loss", False),
        ],
    },
    {
        "question": "Which vitamin significantly enhances the body's absorption of plant-based (non-heme) iron?",
        "category": "Nutrition",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Vitamin C (ascorbic acid) converts ferric iron into more soluble ferrous iron in the gut, multiplying absorption.",
        "options": [
            ("Vitamin C", True),
            ("Vitamin K", False),
            ("Vitamin D", False),
            ("Vitamin E", False),
        ],
    },
    {
        "question": "Which mineral found in nuts, seeds, and leafy greens acts as a natural muscle relaxant that can ease cramping?",
        "category": "Nutrition",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Magnesium regulates neuromuscular contractions and dampens prostaglandin synthesis, helping relieve uterine muscle spasms.",
        "options": [
            ("Sodium", False),
            ("Magnesium", True),
            ("Fluoride", False),
            ("Arsenic", False),
        ],
    },
    {
        "question": "Why should individuals prone to premenstrual bloating moderate high-sodium intake in the luteal phase?",
        "category": "Nutrition",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Excess sodium causes extracellular fluid retention, worsening subjective bloating and breast fullness.",
        "options": [
            ("Sodium causes instant ovulation", False),
            ("Excess sodium increases extracellular water retention", True),
            ("Sodium degrades red blood cells in the liver", False),
            ("Sodium prevents sleep permanently", False),
        ],
    },
    {
        "question": "How do Omega-3 fatty acids (found in flaxseeds, walnuts, and fatty fish) support menstrual comfort?",
        "category": "Nutrition",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Omega-3s compete with arachidonic acid to produce anti-inflammatory prostaglandins (PGE3) instead of inflammatory PGE2.",
        "options": [
            ("They synthesize pro-inflammatory prostaglandins directly", False),
            ("They promote anti-inflammatory pathways that mitigate uterine cramping", True),
            ("They harden the uterine walls", False),
            ("They neutralize stomach acid", False),
        ],
    },
    {
        "question": "True or False: Staying well hydrated with plain water actually helps reduce premenstrual water retention.",
        "category": "Nutrition",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "True. Optimal hydration signals the kidneys to excrete excess retained sodium, reducing fluid pooling and bloating.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "Why do many people experience intense carbohydrate and sweet cravings during the late luteal phase?",
        "category": "Nutrition",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Resting metabolic rate rises slightly, and dropping serotonin levels stimulate brain cravings for carbohydrates, which aid tryptophan transport.",
        "options": [
            ("Resting metabolic rate rises and dipping serotonin stimulates glucose cravings", True),
            ("The stomach shrinks in half", False),
            ("Taste buds stop detecting sugar", False),
            ("Insulin is no longer produced", False),
        ],
    },

    # ==========================================
    # 6. SLEEP & CIRCADIAN HEALTH
    # ==========================================
    {
        "question": "What happens to resting basal body temperature after ovulation during the luteal phase?",
        "category": "Sleep",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Progesterone acting on the hypothalamus raises core basal temperature by 0.3°C to 0.5°C until menses.",
        "options": [
            ("It drops by 2°C", False),
            ("It rises by approximately 0.3°C to 0.5°C", True),
            ("It fluctuates wildly between 40°C and 42°C", False),
            ("It remains completely static year-round", False),
        ],
    },
    {
        "question": "Why can an elevated core body temperature in the late luteal phase impair sleep quality?",
        "category": "Sleep",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Initiation of deep restorative slow-wave sleep biologically requires a drop in core body temperature.",
        "options": [
            ("Deep sleep initiation naturally requires a physiological drop in core temperature", True),
            ("It causes spontaneous waking every 5 minutes without cause", False),
            ("It burns all melatonin instantly", False),
            ("It paralyzes the diaphragm", False),
        ],
    },
    {
        "question": "What is an effective environmental sleep hygiene adaptation during warmer luteal nights?",
        "category": "Sleep",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Keeping the bedroom cooler (18°C–20°C / 65°F–68°F) assists natural thermal dispersion and promotes uninterrupted sleep.",
        "options": [
            ("Keeping the bedroom cool and well-ventilated", True),
            ("Wearing thick thermal snowsuits to bed", False),
            ("Drinking 3 shots of espresso at midnight", False),
            ("Keeping bright fluorescent lights on all night", False),
        ],
    },
    {
        "question": "True or False: Sleep deprivation can elevate cortisol levels and contribute to cycle irregularities.",
        "category": "Sleep",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "True. Chronic sleep disruption activates the hypothalamic-pituitary-adrenal (HPA) axis, suppressing GnRH pulsatility and disrupting cycle regularity.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "How does blue light exposure from smartphones in the evening affect sleep before menstruation?",
        "category": "Sleep",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Blue spectrum light suppresses pineal melatonin secretion, delaying circadian sleep onset latency.",
        "options": [
            ("It enhances melatonin production tenfold", False),
            ("It suppresses melatonin secretion and delays sleep onset", True),
            ("It eliminates menstrual bleeding", False),
            ("It directly causes dysmenorrhea", False),
        ],
    },
    {
        "question": "Which sleep phase is most frequently curtailed during premenstrual hormonal fluctuations?",
        "category": "Sleep",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Studies show that REM sleep proportion and dream recall can be altered during the steep hormonal plunge just prior to menses.",
        "options": [
            ("REM (Rapid Eye Movement) sleep architecture", True),
            ("Stage 1 light sleep only", False),
            ("Hibernate state", False),
            ("There is zero impact on any sleep architecture", False),
        ],
    },

    # ==========================================
    # 7. EXERCISE & MOVEMENT
    # ==========================================
    {
        "question": "How does moderate exercise such as walking or cycling help reduce menstrual discomfort?",
        "category": "Exercise",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Physical activity stimulates circulation, enhances pelvic oxygen delivery, and releases endorphins—the body's natural analgesics.",
        "options": [
            ("By triggering natural endorphin release and improving pelvic blood flow", True),
            ("By stopping the uterine muscles from ever contracting again", False),
            ("By completely freezing the ovaries", False),
            ("By dehydrating the body rapidly", False),
        ],
    },
    {
        "question": "True or False: Swimming in a pool or the ocean while menstruating is safe and sanitary when using appropriate internal products.",
        "category": "Exercise",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "True. Tampons, menstrual cups, or leak-proof swimsuits make swimming hygienic, comfortable, and safe during menstruation.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "What is 'amenorrhea' in the context of extreme athletic training with insufficient caloric intake?",
        "category": "Exercise",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Functional Hypothalamic Amenorrhea (FHA) occurs when low energy availability suppresses GnRH, leading to absence of periods.",
        "options": [
            ("Severe permanent bleeding", False),
            ("The clinical absence or cessation of menstrual periods", True),
            ("A double ovulation event", False),
            ("An increase in menstrual cycle speed", False),
        ],
    },
    {
        "question": "During days of peak flow and physical fatigue, what type of exercise is most restorative?",
        "category": "Exercise",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Gentle stretching, restorative yoga, or light leisurely walking respects natural energy limits without physical strain.",
        "options": [
            ("Exhausting 3-hour marathon training sessions", False),
            ("Gentle restorative movement, light stretching, or rest", True),
            ("Competitive heavy weightlifting to failure", False),
            ("Extreme sprinting without warm-up", False),
        ],
    },
    {
        "question": "What condition represents the 'Female Athlete Triad' in sports medicine?",
        "category": "Exercise",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "The triad comprises low energy availability (with or without disordered eating), menstrual dysfunction (amenorrhea), and decreased bone mineral density.",
        "options": [
            ("Low energy availability, menstrual dysfunction, and low bone mineral density", True),
            ("High blood pressure, high cholesterol, and obesity", False),
            ("Headaches, earaches, and toothaches", False),
            ("Asthma, eczema, and allergies", False),
        ],
    },
    {
        "question": "Why can inverted yoga poses feel uncomfortable for some individuals during peak flow days?",
        "category": "Exercise",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Uterine ligaments are engorged and heavy with blood; holding inversions may cause pelvic heaviness or temporary discomfort.",
        "options": [
            ("Pelvic vascular congestion can cause a subjective sense of heaviness or tension", True),
            ("Blood immediately travels into the heart and lungs", False),
            ("It causes instantaneous toxic shock", False),
            ("Inversions reverse the calendar month", False),
        ],
    },

    # ==========================================
    # 8. EMOTIONAL & MENTAL WELL-BEING
    # ==========================================
    {
        "question": "In which cycle phase do emotional symptoms associated with Premenstrual Syndrome (PMS) typically emerge?",
        "category": "Emotional Well-being",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "PMS emotional changes emerge during the luteal phase (post-ovulation) and resolve within a few days of menstrual onset.",
        "options": [
            ("Luteal phase (1–2 weeks before menstruation)", True),
            ("Follicular phase (days 6–10)", False),
            ("Only on Day 1 of bleeding", False),
            ("Exclusively during menopause", False),
        ],
    },
    {
        "question": "What central neurotransmitter pathway is modulated by fluctuating luteal progesterone metabolites, affecting mood?",
        "category": "Emotional Well-being",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Allopregnanolone (a progesterone metabolite) modulates GABA-A receptors, influencing anxiety, calmness, and mood reactivity.",
        "options": [
            ("GABA and Serotonin receptor signaling", True),
            ("Hemoglobin and Ferritin receptors", False),
            ("Keratin and Melanin receptors", False),
            ("Osteocalcin and Collagen enzymes", False),
        ],
    },
    {
        "question": "What severe clinical mood disorder is characterized by debilitating premenstrual depression, anger, and anxiety?",
        "category": "Emotional Well-being",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Premenstrual Dysphoric Disorder (PMDD) is a severe, debilitating neuroendocrine disorder requiring medical evaluation.",
        "options": [
            ("Bipolar Type 1", False),
            ("Premenstrual Dysphoric Disorder (PMDD)", True),
            ("Seasonal Affective Disorder only", False),
            ("Schizophrenia", False),
        ],
    },
    {
        "question": "True or False: Premenstrual emotional shifts are purely psychological and have no biological or hormonal basis.",
        "category": "Emotional Well-being",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "False. Premenstrual mood fluctuations result from genuine neurochemical interactions between ovarian steroid hormones and central neurotransmitters.",
        "options": [
            ("True", False),
            ("False", True),
        ],
    },
    {
        "question": "How can daily symptom tracking assist individuals in managing premenstrual mood shifts?",
        "category": "Emotional Well-being",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Recognizing recurring cyclic patterns fosters self-compassion, assists in proactive scheduling, and provides objective data for doctors.",
        "options": [
            ("It eliminates the need for sleep", False),
            ("It builds predictive awareness and provides objective data for healthcare discussions", True),
            ("It guarantees mood will never fluctuate again", False),
            ("It resets hormonal levels automatically", False),
        ],
    },
    {
        "question": "Which self-care practice has been demonstrated to reduce premenstrual anxiety and stress hormone levels?",
        "category": "Emotional Well-being",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Mindfulness-based breathing, yoga, and adequate rest activate the parasympathetic nervous system, dampening cortisol spikes.",
        "options": [
            ("Deep diaphragmatic breathing and mindfulness meditation", True),
            ("Consuming 5 energy drinks per day", False),
            ("Isolating completely in darkness without social support", False),
            ("Skipping all meals", False),
        ],
    },
    {
        "question": "When should premenstrual emotional distress prompt a consultation with a healthcare professional?",
        "category": "Emotional Well-being",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "When symptoms severely impair relationships, work, or school, or evoke feelings of hopelessness or self-harm, professional support is vital.",
        "options": [
            ("Only after 30 years of suffering", False),
            ("When feelings severely interfere with daily functioning, work, or safety", True),
            ("Never; emotional distress is trivial", False),
            ("Only if accompanied by a toothache", False),
        ],
    },

    # ==========================================
    # 9. MYTHS AND FACTS
    # ==========================================
    {
        "question": "Myth or Fact: Menstrual blood is toxic body waste filled with harmful poisons.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. Menstrual fluid consists of ordinary blood, cervical mucus, and normal cellular tissue from the endometrium—not toxic waste.",
        "options": [
            ("Myth (It is normal blood and mucosal tissue)", True),
            ("Fact (It contains concentrated bodily toxins)", False),
        ],
    },
    {
        "question": "Myth or Fact: You can never, under any circumstances, get pregnant from intercourse during menstruation.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. Because sperm can survive in the reproductive tract for up to 5 days, early ovulation in individuals with shorter cycles can overlap with menses.",
        "options": [
            ("Fact (Pregnancy is biologically impossible)", False),
            ("Myth (Sperm longevity and early ovulation make pregnancy possible)", True),
        ],
    },
    {
        "question": "Myth or Fact: Severe, debilitating pain that causes school or work absences is 'just part of being a woman' and must be endured silently.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. Disabling pain is not normal and may signal conditions like endometriosis or fibroids, both of which have clinical management options.",
        "options": [
            ("Fact (Pain must always be endured silently)", False),
            ("Myth (Debilitating pain warrants professional medical evaluation)", True),
        ],
    },
    {
        "question": "Myth or Fact: Taking a warm shower or washing your hair while having your period is dangerous.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. Bathing and washing hair are safe and healthy, and warm water can actually help relieve muscular cramps.",
        "options": [
            ("Fact (Washing hair causes blood to congeal)", False),
            ("Myth (Bathing is hygienic, safe, and can alleviate cramping)", True),
        ],
    },
    {
        "question": "Myth or Fact: A tampon can become permanently lost inside the human abdominal cavity.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. The vagina is a closed muscular canal with the cervix at the top. The tiny cervical os cannot accommodate a tampon.",
        "options": [
            ("Fact (A tampon can slip into the stomach)", False),
            ("Myth (The vagina ends at the cervix; objects cannot enter the abdomen)", True),
        ],
    },
    {
        "question": "Myth or Fact: Menstrual cycles among roommates or close friends scientifically sync up to bleed at the exact same time.",
        "category": "Myths and Facts",
        "difficulty": "Medium",
        "question_type": "true_false",
        "explanation": "Myth. Rigorous follow-up research has demonstrated that 'cycle syncing' (the McClintock effect) is a mathematical coincidence of varying cycle lengths.",
        "options": [
            ("Fact (Pheromones force cycles into identical timing)", False),
            ("Myth (Large studies show overlapping is mathematical coincidence)", True),
        ],
    },
    {
        "question": "Myth or Fact: Using a tampon or menstrual cup takes away a person's virginity.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. Virginity is a personal and cultural concept regarding sexual debut, not a physiological state altered by hygiene devices.",
        "options": [
            ("Fact (Using any product alters virginity)", False),
            ("Myth (Hygiene products have nothing to do with sexual debut)", True),
        ],
    },
    {
        "question": "Myth or Fact: Touching plants or cooking sour food during menstruation will spoil the food.",
        "category": "Myths and Facts",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "Myth. This is an ancient cultural taboo unsupported by science. Menstruation has no effect on plants, pickles, or food preparation.",
        "options": [
            ("Fact (Menstruation spoils preserved foods)", False),
            ("Myth (It is an unfounded historical superstition)", True),
        ],
    },

    # ==========================================
    # 10. HEALTH LITERACY & OBSERVATION
    # ==========================================
    {
        "question": "What is the primary benefit of logging menstrual observations (flow, symptoms, mood) consistently?",
        "category": "Health Literacy",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Consistent tracking establishes your personal baseline, making deviations noticeable and providing structured data for clinicians.",
        "options": [
            ("It replaces all medical examinations", False),
            ("It identifies personal baselines and equips you for informed healthcare discussions", True),
            ("It stops your period permanently", False),
            ("It guarantees identical cycle lengths every month", False),
        ],
    },
    {
        "question": "What does health literacy in menstrual health empower individuals to do?",
        "category": "Health Literacy",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Health literacy enables people to understand bodily functions, differentiate normal variations from warning signs, and advocate for their health.",
        "options": [
            ("Self-prescribe prescription medications", False),
            ("Understand bodily cues, recognize anomalies, and make informed well-being decisions", True),
            ("Diagnose complex diseases at home without doctors", False),
            ("Ignore all medical guidelines", False),
        ],
    },
    {
        "question": "What is the medical term for the very first menstrual period experienced during puberty?",
        "category": "Health Literacy",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Menarche is the clinical milestone marking the first menstrual cycle, typically occurring between ages 11 and 14.",
        "options": [
            ("Menarche", True),
            ("Adrenarche", False),
            ("Thelarche", False),
            ("Pubarche", False),
        ],
    },
    {
        "question": "What is the clinical term for cycles that consistently exceed 35 days in length?",
        "category": "Health Literacy",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Oligomenorrhea refers to infrequent menstrual periods with intervals longer than 35 days.",
        "options": [
            ("Polymenorrhea", False),
            ("Oligomenorrhea", True),
            ("Hypomenorrhea", False),
            ("Dyspareunia", False),
        ],
    },
    {
        "question": "What is the approximate total volume of blood lost during a normal, healthy period?",
        "category": "Health Literacy",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Typical blood loss is 30 to 50 milliliters (about 2 to 3 tablespoons) across the entire cycle; exceeding 80 ml is considered heavy.",
        "options": [
            ("30 to 50 milliliters (about 2 to 3 tablespoons)", True),
            ("500 milliliters (half a liter)", False),
            ("1 to 2 liters", False),
            ("Less than 5 drops total", False),
        ],
    },
    {
        "question": "Which of the following describes evidence-based health literacy versus misinformation?",
        "category": "Health Literacy",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Evidence-based literature cites peer-reviewed studies and authoritative clinical societies, avoiding sensational diagnostic claims.",
        "options": [
            ("Anonymous internet blogs with commercial product sponsorships", False),
            ("Peer-reviewed medical literature and verified clinical guidelines with transparent sources", True),
            ("Viral social media videos claiming secret cures", False),
            ("Unverified personal anecdotes with affiliate links", False),
        ],
    },
    {
        "question": "True or False: Cycle irregularities during the first 1 to 2 years after menarche are common due to immature hypothalamic-pituitary-ovarian axis maturation.",
        "category": "Health Literacy",
        "difficulty": "Hard",
        "question_type": "true_false",
        "explanation": "True. The neuroendocrine feedback loops take time to mature in adolescents, leading to frequent anovulatory cycles initially.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },

    # ==========================================
    # 11. HEALTHY HABITS & SELF-CARE
    # ==========================================
    {
        "question": "Why is wearing breathable, cotton underwear recommended for pelvic and menstrual health?",
        "category": "Healthy Habits",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Cotton allows air circulation and absorbs moisture, helping prevent anaerobic bacterial and fungal proliferation.",
        "options": [
            ("It permits air circulation and reduces moisture-driven infection risks", True),
            ("It shortens bleeding days by 50%", False),
            ("It eliminates cramps entirely", False),
            ("It changes menstrual blood color", False),
        ],
    },
    {
        "question": "What is a practical, non-pharmaceutical self-care habit for tracking and managing mild cramps?",
        "category": "Healthy Habits",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Applying local heat, engaging in gentle stretching, staying well-hydrated, and resting provide evidence-supported relief.",
        "options": [
            ("Applying a warm compress, staying hydrated, and light stretching", True),
            ("Refusing to drink water for 3 days", False),
            ("Drinking boiling water directly", False),
            ("Sprinting up mountains with heavy packs", False),
        ],
    },
    {
        "question": "Why should heavily fragranced menstrual products, deodorants, or wipes be avoided?",
        "category": "Healthy Habits",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Synthetic fragrances and preservatives frequently trigger contact dermatitis, vulvar allergy, and vaginal dysbiosis.",
        "options": [
            ("They can trigger allergic contact dermatitis and disrupt sensitive mucosal balance", True),
            ("They make menstrual pads dissolve in seconds", False),
            ("They permanently stop blood circulation", False),
            ("They cause immediate bone fractures", False),
        ],
    },
    {
        "question": "How can maintaining a consistent sleep schedule support hormonal balance?",
        "category": "Healthy Habits",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Circadian clock genes regulate pituitary hormone pulsatility, stabilizing melatonin, cortisol, and reproductive hormones.",
        "options": [
            ("Circadian consistency stabilizes neuroendocrine hormone pulsatility", True),
            ("Sleep schedule has no effect on human biology", False),
            ("It guarantees you will never need food", False),
            ("It stops the heart from beating fast", False),
        ],
    },
    {
        "question": "True or False: Preparing a period care pouch with spare products and wipes helps reduce menstrual anxiety at school or work.",
        "category": "Healthy Habits",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "True. Preparedness reduces anticipation anxiety and ensures hygienic product availability throughout the day.",
        "options": [
            ("True", True),
            ("False", False),
        ],
    },
    {
        "question": "Which herbal tea is frequently used in traditional comfort routines for its mild antispasmodic properties?",
        "category": "Healthy Habits",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Chamomile and ginger teas contain flavonoids and gingerols shown in trials to possess mild soothing and anti-inflammatory properties.",
        "options": [
            ("Pure vinegar", False),
            ("Chamomile or ginger tea", True),
            ("Heavily caffeinated pre-workout syrup", False),
            ("Liquid paraffin", False),
        ],
    },
    {
        "question": "What is the recommended habit when tracking your cycle with an application like MenstruAI?",
        "category": "Healthy Habits",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Logging flow, symptoms, and sensations daily or as they occur ensures data accuracy for personal insights and clinical consultations.",
        "options": [
            ("Recording observations regularly to capture authentic patterns without relying on memory", True),
            ("Making up random dates once a year", False),
            ("Only opening the app if you have an emergency", False),
            ("Logging other people's symptoms instead of your own", False),
        ],
    },

    # ==========================================
    # 12. WHEN TO SEEK PROFESSIONAL HELP
    # ==========================================
    {
        "question": "Which of the following bleeding patterns is a recognized clinical red flag indicating menorrhagia (abnormally heavy bleeding)?",
        "category": "When to Seek Professional Help",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "Soaking through one or more pads or tampons every hour for two consecutive hours is a key criterion for menorrhagia requiring clinical evaluation.",
        "options": [
            ("Soaking through a pad or tampon every hour for 2 or more consecutive hours", True),
            ("Having lighter bleeding on Day 4 than Day 1", False),
            ("Bleeding for 5 total days", False),
            ("Noticing slightly darker blood on the final day", False),
        ],
    },
    {
        "question": "What size of blood clot passed during menstruation warrants clinical discussion with a healthcare provider?",
        "category": "When to Seek Professional Help",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "While tiny clots can be normal during peak flow, passing clots larger than a quarter (2.5 cm / 1 inch) should be evaluated.",
        "options": [
            ("Smaller than a grain of rice", False),
            ("Consistently larger than a quarter (2.5 cm / 1 inch)", True),
            ("Any microscopic clot", False),
            ("Clots are never clinically evaluated", False),
        ],
    },
    {
        "question": "What symptom combination during tampon use requires immediate emergency medical evaluation for suspected TSS?",
        "category": "When to Seek Professional Help",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Sudden high fever, vomiting or diarrhea, a sunburn-like diffuse rash, dizziness, and low blood pressure during tampon use are signs of TSS.",
        "options": [
            ("Sudden high fever, vomiting, dizziness, and a sunburn-like rash", True),
            ("Mild tiredness on Day 1", False),
            ("Slight chocolate craving before bleeding", False),
            ("Waking up 15 minutes earlier than usual", False),
        ],
    },
    {
        "question": "What is 'amenorrhea' that warrants clinical evaluation in an adolescent?",
        "category": "When to Seek Professional Help",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Primary amenorrhea is diagnosed when menstruation has not commenced by age 15 (or 3 years after thelarche) and warrants evaluation.",
        "options": [
            ("Having a period at age 12", False),
            ("Absence of first menstruation by age 15 despite normal secondary sexual characteristics", True),
            ("Having a 30-day cycle", False),
            ("Experiencing mild cramps at age 14", False),
        ],
    },
    {
        "question": "True or False: Severe menstrual pelvic pain that causes vomiting, fainting, or missed school/work days is considered normal and does not need medical attention.",
        "category": "When to Seek Professional Help",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "False. Disabling pain is not normal and warrants a compassionate, comprehensive clinical investigation for conditions such as endometriosis.",
        "options": [
            ("True", False),
            ("False (It warrants medical evaluation)", True),
        ],
    },
    {
        "question": "What should an individual do if they experience unexpected bleeding between menstrual cycles (intermenstrual bleeding)?",
        "category": "When to Seek Professional Help",
        "difficulty": "Medium",
        "question_type": "single_choice",
        "explanation": "Intermenstrual bleeding or post-coital bleeding should be documented and evaluated by a healthcare professional to identify potential cervical or uterine causes.",
        "options": [
            ("Ignore it permanently", False),
            ("Log the dates and symptoms and schedule a consultation with a qualified doctor", True),
            ("Double their physical exercise immediately", False),
            ("Stop eating vegetables", False),
        ],
    },
    {
        "question": "Which diagnostic specialist is primarily trained in female reproductive and pelvic health?",
        "category": "When to Seek Professional Help",
        "difficulty": "Easy",
        "question_type": "single_choice",
        "explanation": "An Obstetrician-Gynecologist (OB-GYN) or adolescent gynecologist specializes in female reproductive medicine and cycle care.",
        "options": [
            ("Obstetrician-Gynecologist (OB-GYN)", True),
            ("Orthopedic surgeon", False),
            ("Podiatrist", False),
            ("Ophthalmologist", False),
        ],
    },
    {
        "question": "True or False: MenstruAI provides automated medical diagnoses and replaces certified physician care.",
        "category": "When to Seek Professional Help",
        "difficulty": "Easy",
        "question_type": "true_false",
        "explanation": "False. MenstruAI is an educational literacy and observation platform. It does not diagnose, prescribe, or substitute for healthcare professionals.",
        "options": [
            ("True", False),
            ("False", True),
        ],
    },
    {
        "question": "How does the negative feedback loop of estradiol and progesterone on GnRH during the luteal phase prevent secondary follicular maturation?",
        "category": "Menstrual Health Basics",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "High circulating progesterone combined with estradiol acts on hypothalamic and pituitary receptors to suppress pulsatile GnRH and FSH secretion, halting new follicular recruitment.",
        "options": [
            ("By stimulating extreme spikes in thyroid hormones", False),
            ("By suppressing pulsatile release of GnRH from the hypothalamus and lowering FSH/LH", True),
            ("By degrading the uterine vascular bed", False),
            ("By disabling ovarian blood vessels completely", False),
        ],
    },
    {
        "question": "Which enzyme converts androstenedione to estrone within ovarian granulosa cells under FSH stimulation?",
        "category": "Menstrual Health Basics",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Under the two-cell, two-gonadotropin model, thecal cells synthesize androgens, which granulosa cells convert to estrogens via the enzyme aromatase (CYP19A1).",
        "options": [
            ("Aromatase (CYP19A1)", True),
            ("Amylase", False),
            ("Lactate dehydrogenase", False),
            ("DNA polymerase III", False),
        ],
    },
    {
        "question": "What is the primary microbiological mechanism behind Toxic Shock Syndrome (TSS) associated with prolonged tampon usage?",
        "category": "Menstrual Hygiene",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "TSS is caused when certain strains of Staphylococcus aureus proliferate in an oxygen-rich tampon environment and secrete toxic shock syndrome toxin-1 (TSST-1), a superantigen activating widespread T-cells.",
        "options": [
            ("Fungal candida overgrowth fermenting menstrual fluid", False),
            ("Superantigen TSST-1 exotoxin production by Staphylococcus aureus causing systemic cytokine release", True),
            ("E. coli biofilm formation in the fallopian tubes", False),
            ("Viral latency in cervical lymph nodes", False),
        ],
    },
    {
        "question": "What biochemical mechanism drives the severe uterine hypercontractility in Primary Dysmenorrhea?",
        "category": "Symptoms",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Excessive intrauterine production and release of cyclooxygenase-derived PGF2-alpha prostaglandins induce uterine hypercontractility, vasoconstriction, and localized myometrial ischemia.",
        "options": [
            ("Excessive prostaglandin F2-alpha (PGF2a) stimulating intense myometrial ischemia and contractions", True),
            ("Lack of lactic acid in abdominal muscles", False),
            ("Hypocalcemia triggering bone remodeling", False),
            ("Sudden drop in systemic insulin", False),
        ],
    },
    {
        "question": "Which diagnostic clinical characteristic reliably distinguishes physiological Mittelschmerz from an acute surgical abdomen?",
        "category": "Symptoms",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Mittelschmerz presents as mild, unilateral lower abdominal pain occurring mid-cycle (days 12–16) corresponding with pre-ovulatory follicular expansion and rupture, typically resolving in under 24–48 hours.",
        "options": [
            ("High spiking fever and generalized peritonitis", False),
            ("Mild unilateral mid-cycle discomfort resolving within 24 to 48 hours without systemic deterioration", True),
            ("Persistent heavy bright-red bleeding for three weeks", False),
            ("Inability to move upper extremities", False),
        ],
    },
    {
        "question": "How does excessive dietary phytic acid (phytates) affect non-heme iron absorption during menstruation?",
        "category": "Nutrition",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Phytates present in unsoaked seeds, grains, and legumes chelate ferric iron into insoluble complexes within the intestinal lumen, significantly decreasing its mucosal absorption.",
        "options": [
            ("Phytates chelate ferric ions into insoluble complexes, impeding duodenal absorption", True),
            ("Phytates accelerate iron excretion through perspiration", False),
            ("Phytates directly destroy red blood cells in the stomach", False),
            ("Phytates permanently convert hemoglobin into myoglobin", False),
        ],
    },
    {
        "question": "Why does the mid-luteal rise in core body temperature by 0.3°C to 0.5°C frequently alter sleep architecture?",
        "category": "Sleep",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Progesterone acts on the thermoregulatory center of the preoptic anterior hypothalamus, raising the baseline temperature set-point and diminishing the nocturnal temperature drop necessary for deep slow-wave sleep.",
        "options": [
            ("Progesterone increases the hypothalamic thermal set-point, impeding the circadian drop in body temperature required for deep sleep", True),
            ("Estrogen shuts down the visual cortex at night", False),
            ("Melatonin receptors are permanently destroyed by progesterone", False),
            ("Lactic acid accumulates in brain tissues during the luteal phase", False),
        ],
    },
    {
        "question": "In the Female Athlete Triad, what primary neuroendocrine alteration triggers functional hypothalamic amenorrhea?",
        "category": "Exercise",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Low energy availability suppresses adipocyte leptin release, which in turn diminishes hypothalamic kisspeptin and disrupts pulsatile GnRH release, leading to low LH/FSH and hypoestrogenism.",
        "options": [
            ("Low energy availability suppresses leptin and kisspeptin, dampening pulsatile GnRH secretion", True),
            ("Excessive testosterone converts directly into cortisol in the lungs", False),
            ("Growth hormone destroys ovarian follicles upon strenuous running", False),
            ("Endorphins directly block progesterone receptor gene expression", False),
        ],
    },
    {
        "question": "Which neuroactive metabolite of progesterone is implicated in modulating central GABA-A receptors in Premenstrual Dysphoric Disorder (PMDD)?",
        "category": "Emotional Well-being",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Allopregnanolone is a potent positive allosteric modulator of GABA-A receptors; individuals with PMDD exhibit abnormal receptor subunit sensitivity to fluctuations in allopregnanolone.",
        "options": [
            ("Allopregnanolone", True),
            ("Acetylcholine", False),
            ("Cholecystokinin", False),
            ("Dihydrotestosterone", False),
        ],
    },
    {
        "question": "When reviewing an ultrasound report, what typical endometrial thickness is expected immediately following complete menstruation (early proliferative phase)?",
        "category": "Health Literacy",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Immediately after menstrual shedding (Day 4–6), the basal endometrial layer is thin, typically measuring between 2 to 4 mm on pelvic ultrasound.",
        "options": [
            ("16 to 22 mm", False),
            ("2 to 4 mm", True),
            ("Exactly 35 mm", False),
            ("Over 50 mm", False),
        ],
    },
    {
        "question": "In the internationally accepted FIGO PALM-COEIN system for abnormal uterine bleeding, which component refers to structural lesions?",
        "category": "When to Seek Professional Help",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "PALM represents structural anatomical lesions: Polyp, Adenomyosis, Leiomyoma (fibroid), and Malignancy/hyperplasia, assessed via imaging and histopathology.",
        "options": [
            ("PALM (Polyp, Adenomyosis, Leiomyoma, Malignancy)", True),
            ("COEIN (Coagulopathy, Ovulatory, Endometrial, Iatrogenic, Not classified)", False),
            ("Both PALM and COEIN are identical categories", False),
            ("Neither represents clinical terminology", False),
        ],
    },
    {
        "question": "What clinical feature differentiates unpredictable abnormal uterine bleeding (AUB) from normal physiological ovulatory spotting?",
        "category": "When to Seek Professional Help",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Normal ovulatory spotting is brief (12–36 hours), light, and coincides with the mid-cycle LH surge. In contrast, abnormal bleeding is erratic, prolonged, heavy, or unpredictable.",
        "options": [
            ("AUB is erratic, prolonged, or substantial, whereas ovulatory spotting is very brief, faint, and predictably timed with mid-cycle", True),
            ("Ovulatory spotting only occurs during deep sleep", False),
            ("AUB only occurs during childhood", False),
            ("Ovulatory spotting lasts for 15 continuous days", False),
        ],
    },
    {
        "question": "Why is medical-grade silicone considered biochemically inert and safe for extended internal menstrual collection?",
        "category": "Menstrual Products",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Medical-grade silicone is non-porous, hypoallergenic, resistant to bacterial colonization, and does not absorb vaginal moisture or alter the delicate acidic lactobacilli vaginal ecosystem.",
        "options": [
            ("It is non-porous, non-absorptive, and chemically unreactive with mucosal membranes and lactobacilli", True),
            ("It dissolves into the bloodstream after 12 hours", False),
            ("It emits infrared heat waves to stop cramping", False),
            ("It contains synthetic antibiotics embedded in its matrix", False),
        ],
    },
    {
        "question": "Why can anovulatory cycles in conditions like PCOS still produce unpredictable episodes of heavy vaginal bleeding?",
        "category": "Myths and Facts",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Without ovulation and corpus luteum formation, progesterone is absent. Unopposed estrogen causes sustained endometrial proliferation until the tissue outgrows its vascular support and collapses asynchronously (estrogen breakthrough bleeding).",
        "options": [
            ("Unopposed estrogen drives endometrial hyperplasia until it outgrows its blood supply, causing chaotic breakthrough shedding", True),
            ("The ovaries produce large quantities of stomach acid", False),
            ("The uterus fills with air bubbles and ruptures", False),
            ("Blood pressure in the legs rises excessively", False),
        ],
    },
    {
        "question": "Why is pre-conceptional high-dose NSAID use sometimes cautioned immediately prior to expected ovulation?",
        "category": "Healthy Habits",
        "difficulty": "Hard",
        "question_type": "single_choice",
        "explanation": "Ovulation is an inflammatory-like physiological process requiring COX-2 enzymes and prostaglandins to rupture the follicular apex; heavy NSAID inhibition can delay or prevent luteinized unruptured follicle release.",
        "options": [
            ("COX-2 inhibition can suppress the prostaglandin cascade necessary for ovarian follicular wall rupture", True),
            ("NSAIDs turn all cervical mucus into acid", False),
            ("NSAIDs cause immediate destruction of fallopian tubes", False),
            ("NSAIDs permanently block iron absorption for 1 year", False),
        ],
    },
]

